name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48dd96de9b871ee78e90e50e4af356c10437aaaf9335b94d8aac1240e69201f8"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
