name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10b8d116eea2d43a070bbe9d2ad83c5315c47e36d8100a8d33bd86814fe70564"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
