name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c905d1fd1ae0e5192a55d17e15559060480c536dba574a7ea4270e753d9912f3"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
