name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "051990e533f8799400d4dc56752c4f5219524ccde9b5bf70fedcb60e406f510e"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
