name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d51a8e82ce9514e9a8407f6aec27be0de6579d96700928b3ca6b1051f703cef9"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
