name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aeb690a039899fe88370f52568ca995b3d2705fa0c64fb5dfa196dd2d3b79e9"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
