name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae5ace9488026e292089c866667e4dbc715e60a18f5b5f867e470b1456c8ca98"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
