name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81a8e5e901e091289b9b1e196826d5283622dbde448ef74232f1e4ae6573c063"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
