name = "MGDCASPack"
author = "Cromptons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa27f154e2d00430ace2e47622101dd809be974b84196b54949ecd8b77759e5"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
