!!dev.wuffs.squatgrow.config.SquatGrowConfig
allowAdventureTwerking: true
chance: 0.15
debug: false
enableMysticalCrops: true
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium', 'minecraft:cobblestone',
  'minecraft:chiseled_stone_bricks', 'minecraft:cracked_stone_bricks', 'minecraft:mossy_stone_bricks',
  'minecraft:stone_bricks', 'minecraft:stone', 'minecraft:stone_slab', 'minecraft:stone_stairs',
  'minecraft:stone_brick_slab', 'minecraft:stone_brick_stairs', 'minecraft:stone_brick_wall',
  'minecraft:cobblestone_wall', 'minecraft:cobblestone_slab', 'minecraft:cobblestone_stairs',
  'minecraft:mossy_cobblestone', 'minecraft:mossy_cobblestone_slab', 'minecraft:mossy_cobblestone_stairs',
  'minecraft:mossy_cobblestone_wall', 'minecraft:bricks', 'minecraft:brick_slab',
  'minecraft:brick_stairs', 'minecraft:brick_wall', 'minecraft:iron_block', 'minecraft:iron_bars',
  'minecraft:iron_door', 'minecraft:iron_trapdoor', 'minecraft:copper_block', 'minecraft:oak_leaves',
  'minecraft:spruce_leaves', 'minecraft:birch_leaves', 'minecraft:jungle_leaves',
  'minecraft:acacia_leaves', 'minecraft:dark_oak_leaves', 'immersive_weathering:mossy_bricks',
  'immersive_weathering:mossy_brick_slab', 'immersive_weathering:mossy_brick_stairs',
  'immersive_weathering:mossy_brick_wall', 'immersive_weathering:mossy_stone', 'immersive_weathering:mossy_stone_slab',
  'immersive_weathering:mossy_stone_stairs', 'immersive_weathering:mossy_stone_wall',
  'immersive_weathering:mossy_chiseled_stone_bricks', 'immersive_weathering:ivy',
  'minecraft:rooted_dirt', 'immersive_weathering:rooted_grass_block']
range: 4
requireHoe: true
useWhitelist: false
